In [1]:
import pandas as pd
import numpy as np

In [2]:
preprocessed_data=pd.read_csv("C:\\Users\\HP\\Downloads\\Absenteeism_preprocessed.csv")

In [3]:
preprocessed_data.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

In [4]:
targets=np.where(preprocessed_data['Absenteeism Time in Hours']>(preprocessed_data['Absenteeism Time in Hours']).median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
preprocessed_data['Excessive Absenteeism']=targets
preprocessed_data.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

##A comment on the targets

In [7]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [8]:
data_with_targets=preprocessed_data.drop(['Absenteeism Time in Hours'],axis=1)

In [9]:
data_with_targets is preprocessed_data

False

In [10]:
data_with_targets.shape

(700, 15)

In [12]:
unscaled_inputs=data_with_targets.iloc[:,:14]
unscaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  
0               30          0         2    1  
1               31          0         1    0  
2               31          0         0    0  
3               24          0         2    0  
4               30          0         2    1

In [13]:
from sklearn.preprocessing import StandardScaler
absenteeism_scalar= StandardScaler()

In [14]:
absenteeism_scalar.fit(unscaled_inputs)

StandardScaler()

In [15]:
scaled_inputs=absenteeism_scalar.transform(unscaled_inputs)
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [16]:
scaled_inputs.shape

(700, 14)

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
train_test_split(scaled_inputs,targets)


[array([[ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
          2.67996851, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927, -0.58968976],
        ...,
        [-0.57735027, -0.09298136,  3.17979734, ...,  2.23224237,
         -0.91902997, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          2.67996851, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  0.26848661],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -

In [19]:
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)

In [20]:
print(x_train.shape,y_train.shape)

(560, 14) (560,)


In [21]:
print(x_test.shape,y_test.shape)

(140, 14) (140,)


##Logistic regression model

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [24]:
reg=LogisticRegression()
reg.fit(x_train,y_train)

LogisticRegression()

In [25]:
reg.score(x_train,y_train)

0.7803571428571429

## MANUALLY CHECK THE ACCURACY

In [27]:
model_outputs=reg.predict(x_train)
model_outputs

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [28]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [29]:
model_outputs == y_train

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [30]:
np.sum(model_outputs == y_train)

437

In [31]:
model_outputs.shape[0]

560

In [32]:
np.sum(model_outputs == y_train)/model_outputs.shape[0]

0.7803571428571429

In [33]:
reg.intercept_

array([-0.21102398])

In [34]:
reg.coef_

array([[ 2.06986858,  0.33028689,  1.56236468,  1.31054482,  0.02588386,
        -0.08649155,  0.72352943, -0.06072562, -0.2052754 , -0.02828267,
         0.3257168 , -0.16073453,  0.3815691 , -0.32129179]])

In [35]:
feature_name=unscaled_inputs.columns.values
feature_name

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [36]:
summary_table=pd.DataFrame(columns=['Feature name'],data=feature_name)
summary_table['coefficients']=np.transpose(reg.coef_)
summary_table

Feature name  coefficients
0                  Reason_1      2.069869
1                  Reason_2      0.330287
2                  Reason_3      1.562365
3                  Reason_4      1.310545
4               Month Value      0.025884
5           Day of the Week     -0.086492
6    Transportation Expense      0.723529
7          Distance to Work     -0.060726
8                       Age     -0.205275
9   Daily Work Load Average     -0.028283
10          Body Mass Index      0.325717
11                Education     -0.160735
12                 Children      0.381569
13                      Pet     -0.321292

In [37]:
summary_table.index=summary_table.index+1

In [38]:
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

Feature name  coefficients
0                 Intercept     -0.211024
1                  Reason_1      2.069869
2                  Reason_2      0.330287
3                  Reason_3      1.562365
4                  Reason_4      1.310545
5               Month Value      0.025884
6           Day of the Week     -0.086492
7    Transportation Expense      0.723529
8          Distance to Work     -0.060726
9                       Age     -0.205275
10  Daily Work Load Average     -0.028283
11          Body Mass Index      0.325717
12                Education     -0.160735
13                 Children      0.381569
14                      Pet     -0.321292

## testing the model

In [40]:
reg.score(x_test,y_test)

0.7285714285714285

In [41]:
predicted_proba=reg.predict_proba(x_test)
predicted_proba

array([[0.76471409, 0.23528591],
       [0.61167855, 0.38832145],
       [0.40767059, 0.59232941],
       [0.78557457, 0.21442543],
       [0.06075314, 0.93924686],
       [0.26771935, 0.73228065],
       [0.28626672, 0.71373328],
       [0.06687796, 0.93312204],
       [0.75878872, 0.24121128],
       [0.76521137, 0.23478863],
       [0.47338669, 0.52661331],
       [0.13567347, 0.86432653],
       [0.04163776, 0.95836224],
       [0.69555394, 0.30444606],
       [0.20586587, 0.79413413],
       [0.47708783, 0.52291217],
       [0.49325552, 0.50674448],
       [0.5385909 , 0.4614091 ],
       [0.37778738, 0.62221262],
       [0.02923023, 0.97076977],
       [0.7340362 , 0.2659638 ],
       [0.77718245, 0.22281755],
       [0.4260149 , 0.5739851 ],
       [0.44253864, 0.55746136],
       [0.15300393, 0.84699607],
       [0.76013758, 0.23986242],
       [0.45641034, 0.54358966],
       [0.89837466, 0.10162534],
       [0.16321201, 0.83678799],
       [0.76855864, 0.23144136],
       [0.

In [42]:
predicted_proba[:,1]

array([0.23528591, 0.38832145, 0.59232941, 0.21442543, 0.93924686,
       0.73228065, 0.71373328, 0.93312204, 0.24121128, 0.23478863,
       0.52661331, 0.86432653, 0.95836224, 0.30444606, 0.79413413,
       0.52291217, 0.50674448, 0.4614091 , 0.62221262, 0.97076977,
       0.2659638 , 0.22281755, 0.5739851 , 0.55746136, 0.84699607,
       0.23986242, 0.54358966, 0.10162534, 0.83678799, 0.23144136,
       0.41408328, 0.74153958, 0.7008613 , 0.52928416, 0.22281755,
       0.61594634, 0.25772832, 0.83185767, 0.47494375, 0.60672861,
       0.2424275 , 0.41695579, 0.23470549, 0.09844889, 0.82776712,
       0.73210957, 0.76165752, 0.24123202, 0.27215577, 0.20124285,
       0.49892458, 0.07038119, 0.70505423, 0.26216528, 0.8684819 ,
       0.44148327, 0.95231371, 0.29202077, 0.07809625, 0.07661661,
       0.74434135, 0.68006647, 0.28705942, 0.85845493, 0.23884712,
       0.23733866, 0.01167321, 0.24484425, 0.8442063 , 0.31178283,
       0.24389933, 0.07867904, 0.92229144, 0.46714437, 0.65160

## save the model

In [44]:
import pickle

In [45]:
with open('model','wb') as file:
    pickle.dump(reg,file)
    

In [46]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scalar,file)